/*!
 * Copyright (c) 2024 PLANKA Software GmbH
 * Licensed under the Fair Use License: https://github.com/plankanban/planka/blob/master/LICENSE.md
 */

const FILE_IS_TOO_BIG = 'FILE_IS_TOO_BIG';
const NOT_ENOUGH_STORAGE = 'NOT_ENOUGH_STORAGE';
const EMPTY_TRASH = 'EMPTY_TRASH';
const SOURCE_CARD_NOT_COPYABLE = 'SOURCE_CARD_NOT_COPYABLE';
const SOURCE_CARD_NOT_MOVABLE = 'SOURCE_CARD_NOT_MOVABLE';
const WIP_LIMIT_EXCEEDED = 'WIP_LIMIT_EXCEEDED';
const WIP_LIMIT_WARN = 'WIP_LIMIT_WARN';
const SYSTEM_WIP_LIMIT_EXCEEDED = 'SYSTEM_WIP_LIMIT_EXCEEDED';
const SYSTEM_WIP_LIMIT_WARN = 'SYSTEM_WIP_LIMIT_WARN';
const WIP_LIMIT_SUM_EXCEEDS_SYSTEM_LIMIT = 'WIP_LIMIT_SUM_EXCEEDS_SYSTEM_LIMIT';
const CARD_HAS_ACTIVE_BLOCKERS = 'CARD_HAS_ACTIVE_BLOCKERS';

export default {
  FILE_IS_TOO_BIG,
  NOT_ENOUGH_STORAGE,
  EMPTY_TRASH,
  SOURCE_CARD_NOT_COPYABLE,
  SOURCE_CARD_NOT_MOVABLE,
  WIP_LIMIT_EXCEEDED,
  WIP_LIMIT_WARN,
  SYSTEM_WIP_LIMIT_EXCEEDED,
  SYSTEM_WIP_LIMIT_WARN,
  WIP_LIMIT_SUM_EXCEEDS_SYSTEM_LIMIT,
  CARD_HAS_ACTIVE_BLOCKERS,
};
